### ISSUE TITLE
Empty Workspace Error

### ISSUE THREAD

**Issue by CelsiaSolaraStarflare** [SchBenedikt/Text-Editor#12]
**Is your feature request related to a problem? Please describe.**
When closing all the tabs for editing text files, if any keys are pressed on the blank canvas would cause an error. The error would cause the whole program to froze and needs to be restarted to continue using. 

**Describe the solution you'd like**
Maybe we can add something, such as when any key is pressed on the blank canvas, then we make a window showing a request to "Add new tab[yes/no]" and make that the highest priority in the program to avoid the program from having an error, while the user can also continue to add tab.

**Describe alternatives you've considered**
Correct the program's main loop to try except so that the lines executed(errors) will not cause the program to froze.
<img width="912" alt="Screenshot 2024-01-01 at 11 04 10 PM" src="https://github.com/SchBenedikt/Text-Editor/assets/136956908/5e03dc8c-2528-413c-8408-d2889174f084">

**Comment by SchBenedikt** [comment]
I changed the code so that the application normally closes immediately when the last tab is closed. Does that work for you too?

**Comment by CelsiaSolaraStarflare** [comment]
yep it is fixed.
