### ISSUE TITLE
Upload files to Github repos

### ISSUE THREAD

**Issue by SchBenedikt** [SchBenedikt/Text-Editor#8]
With the latest update you can now edit files from Github repositories. You should then be able to upload these edited files again. This probably works best via API.

**Comment by Telephos** [comment]
I pulled the latest revisions. Currently my project tab doesn't work at all. Can you clarify for me what it's supposed to show?

**Comment by SchBenedikt** [comment]
![image](https://github.com/SchBenedikt/Text-Editor/assets/137323528/0ba73ce6-ba7d-4bbd-be65-9de1688eb4ab)
![image](https://github.com/SchBenedikt/Text-Editor/assets/137323528/dda22c8c-0842-4e54-bda4-0a888eff25f7)
![image](https://github.com/SchBenedikt/Text-Editor/assets/137323528/175e8b54-019f-4ccc-a8ea-cca17789dd78)
You should be able to register in the "File" menu when you go to the last button. That means linking your Github account.
If you then restart the app, your projects should also appear.
In the registration process, you will be forwarded to Github. If you appear any error here, open the URL with the corresponding port in the incognito tab.

**Comment by Telephos** [comment]
Ok, I'll try to work on this. I'm not able to connect to my github repo at all, just get a 500 internal server error.

**Comment by SchBenedikt** [comment]
Yes, I sometimes see the internal server error too. But then try to open the link (localhost:5000) in the Icognitotab - the error no longer appears (for me).

**Comment by SchBenedikt** [comment]
See on #24

**Comment by SchBenedikt** [comment]
> Ok, I'll try to work on this. I'm not able to connect to my github repo at all, just get a 500 internal server error.

@Telephos I solved the issue.
I changed the code directly without PR. The new code is:

```python
    def start_webserver(self):
        def run_flask_app():
            app.run(host="127.0.0.1", port=5000)

        flask_thread = threading.Thread(target=run_flask_app)
        flask_thread.start()

        url = "http://127.0.0.1:5000"
```
